name: FlatMcFFA
main: ai.brandvibe.flatmcffa.FlatMcFFAPlugin
version: 1.0.0
api-version: '1.20'
author: BrandVibe
commands:
  ffa:
    description: FlatMcFFA root command
    usage: /ffa <setarena|arenas|arena|setkit|kits|kit|reload>
    permission: flatmcffa.use
permissions:
  flatmcffa.use:
    default: true
  flatmcffa.admin:
    default: op
